import {BrainWorld} from './world.js?v=5';
import {Soundscape} from './audio.js';
import {CHAPTERS,STRUCTURES,SOURCES,TRANSMITTERS,NETWORKS,EXPERIENCES,WHATIFS,SURPRISES,SEARCH_SYSTEMS} from './content.js';

const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={play:'M8 5l11 7-11 7z',pause:'M9 5v14M15 5v14',next:'M5 12h14M14 7l5 5-5 5',prev:'M19 12H5m5-5-5 5 5 5',sound:'M11 5 6 9H3v6h3l5 4zM15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',mute:'M11 5 6 9H3v6h3l5 4zM16 9l5 6m0-6-5 6',menu:'M4 6h16M4 12h16M4 18h16',rotate:'M20 7v5h-5M4 17v-5h5M5 8a8 8 0 0 1 13-3l2 3M4 16l2 3a8 8 0 0 0 13-3',zoom:'M12 5v14M5 12h14',minus:'M5 12h14',xray:'M3 12h18M12 3v18M5 5l14 14M5 19 19 5',explode:'M9 4v16M15 4v16M6 8l-4 4 4 4m12-8 4 4-4 4',connections:'M5 5l14 7L5 19V5m14 7H5',reset:'M4 10a8 8 0 1 1 1 8M4 4v6h6',pan:'M12 2v20M2 12h20M9 5l3-3 3 3M9 19l3 3 3-3M5 9l-3 3 3 3m14-6 3 3-3 3',focus:'M4 9V4h5m6 0h5v5m0 6v5h-5M9 20H4v-5M9 12h6M12 9v6',search:'M21 21l-6-6M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14',info:'M12 11v6M12 7h.01M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20',voice:'M9 4v8a3 3 0 0 0 6 0V4a3 3 0 0 0-6 0M5 11v1a7 7 0 0 0 14 0v-1M12 19v3',spark:'M12 3l2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3z',section:'M5 3v18M9 6h11v12H9M9 12h11',cc:'M3 5h18v14H3zM10 9H7v6h3m7-6h-3v6h3'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.info}"/></svg>`;
const btn=(action,label,ico='',cls='',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${ico?icon(ico):''}${label}</button>`;
const sourceLink=key=>SOURCES[key]?`<a class="source-link" href="${SOURCES[key][1]}" target="_blank" rel="noopener noreferrer">${esc(SOURCES[key][0])} ↗</a>`:'';
const state={started:false,intro:false,introStart:0,introStep:-1,c:0,s:0,mode:'journey',paused:false,elapsed:0,selected:null,special:null,search:'',captions:true,deep:false,viewMenu:false,network:'default',transmitter:'glutamate',receptor:'d1',speed:1000,myelin:true,sleep:'wake',scale:0,illusion:false,practice:0,practiceCount:0,context:false,body:'normal',pathStep:-1,pathStart:-100,signalStart:-100,catcher:.5,catchStart:-100,catchDone:false,goState:'idle',goStart:0,goTimer:null,visited:new Set(),surprise:-1,feedback:'',lastUser:false};
const audio=new Soundscape();let world=null,worldError=false,previous=performance.now(),uiFrame=0,demoAnimation=0,toastTimer=null,labelCache='';
const current=()=>CHAPTERS[state.c].scenes[state.s];
function activeScene(){if(state.special?.type==='surprise'){const x=SURPRISES[state.special.index];return {...x,hook:x.text,text:'',evidence:'We know'};}if(state.special?.type==='whatif'){const x=WHATIFS[state.special.index];return {...x,hook:'What can disruption teach us about this system?',view:'xray',demo:'whatif'};}return current();}
const allSceneCount=CHAPTERS.reduce((n,c)=>n+c.scenes.length,0);
function toast(text){clearTimeout(toastTimer);$('#toast')?.remove();const el=document.createElement('div');el.id='toast';el.className='toast';el.setAttribute('role','status');el.textContent=text;$('#interface').append(el);toastTimer=setTimeout(()=>el.remove(),5100);}
function renderIntro(){
 $('#interface').innerHTML=`<div class="intro-cover" id="intro-cover"><div class="intro-kicker">AN INTERACTIVE DOCUMENTARY</div><h1>Inside the<br>human brain.</h1><p class="intro-subtitle">A journey into the world that makes you, you.<br>10 chapters · About 25 minutes · Explore at your pace</p><div class="enter-buttons">${btn('begin','Enter the brain','next','enter-main')}${btn('begin-silent','Enter silently','','enter-silent')}</div><div class="intro-foot">Sound and optional device narration · Captions throughout</div></div>`;
}
function startIntro(sound){
 state.started=true;state.intro=true;state.introStart=performance.now();state.introStep=-1;audio.start(sound);audio.mode='intro';world?.setView('intro',[],true);if(world){world.brain.visible=false;world.human.visible=true;world.rotating=false;}
 $('#interface').innerHTML=`<div class="intro-cover started" id="intro-cover"><div id="cinema-text" class="cinema-caption"></div>${btn('sound','',sound?'sound':'mute','intro-sound icon-button','aria-label="Toggle sound"')}${btn('skip-intro','Skip opening','','intro-skip')}</div>`;
 if(worldError){state.introStart-=25000;}
}
function tickIntro(now){const t=(now-state.introStart)/1000;const parts=[{at:1,text:'You are about to enter the most complex system we know of.',small:true},{at:7,text:'Your brain.'},{at:13,text:'~86 billion neurons',stat:true},{at:19,text:'Trillions of connections',stat:true},{at:25,text:'One human brain',stat:true},{at:29,text:'Let’s go inside.'}];let idx=-1;for(let i=0;i<parts.length;i++)if(t>=parts[i].at)idx=i;
 if(idx!==state.introStep&&idx>=0){state.introStep=idx;const p=parts[idx],el=$('#cinema-text');if(el){el.className=`cinema-caption ${p.stat?'stat':''}`;el.innerHTML=`<div class="${p.small?'cinema-small':'cinema-large'}">${esc(p.text)}</div>`;}audio.speak(p.text);if(idx===1&&world){world.brain.visible=true;world.fly(new world.camera.position.constructor(6,2.5,8),new world.camera.position.constructor(0,-.1,0));}if(idx===5)world?.setView('cortex',['cortex']);}
 if(t>33)enterJourney(0,0);
}
function enterJourney(c=state.c,s=state.s){state.intro=false;state.mode='journey';state.special=null;state.selected=null;state.search='';loadScene(c,s);}
function loadScene(c,s){clearTimeout(state.goTimer);state.c=Math.max(0,Math.min(CHAPTERS.length-1,c));state.s=Math.max(0,Math.min(CHAPTERS[state.c].scenes.length-1,s));state.elapsed=0;state.paused=false;state.deep=false;state.special=null;state.selected=null;state.pathStep=-1;state.pathStart=-100;state.feedback='';state.finaleStart=0;state.finaleStage=-1;state.goState='idle';state.visited.add(state.c);state.sleep=current().sleep||'wake';state.scaleStart=current().demo==='scale'?performance.now():0;state.scaleStage=-1;state.scale=0;state.network=current().network in NETWORKS?current().network:'default';configureWorld(current());render();narrate();}
function configureWorld(s){if(!world)return;world.playing=!state.paused;world.setView(s.view??'brain',s.focus??[]);world.rotating=!world.reduced;world.speed=state.speed;world.setMyelin(state.myelin);if(s.network)world.setConnections(true,s.network);if(s.experience)world.setConnections(true,s.experience);if(s.glial)world.setGlia(s.glial);if(s.view==='sleep')world.setConnections(true,'default');audio.mode=s.view??'brain';}
function narrate(){const s=activeScene();const d=state.selected?STRUCTURES[state.selected]:null;audio.speak(d?`${d.name}. ${d.where} ${d.does} ${d.care}`:`${s.title} ${s.hook} ${s.text??''}`);}
function next(){if(state.special){state.special=null;loadScene(state.c,state.s);return;}if(state.s+1<CHAPTERS[state.c].scenes.length)loadScene(state.c,state.s+1);else if(state.c+1<CHAPTERS.length)loadScene(state.c+1,0);else openExplore();}
function prev(){if(state.s>0)loadScene(state.c,state.s-1);else if(state.c>0)loadScene(state.c-1,CHAPTERS[state.c-1].scenes.length-1);}
function pause(p=!state.paused){state.paused=p;if(world)world.playing=!p;audio.pause(p);const b=$('[data-action="play"]');if(b)b.innerHTML=`<span class="play-ring">${icon(p?'play':'pause')}</span>${p?'Play journey':'Pause journey'}`;}
function selectStructure(id){if(!STRUCTURES[id])return;state.selected=id;state.deep=false;state.paused=true;if(world){world.playing=true;world.focus=[id];if(['hippocampus','amygdala','thalamus','basal','hypothalamus','ventricles','callosum'].includes(id))world.xray=true;world.applyFocus();world.rotating=false;}audio.cancel();render();if(current().challenge===id&&state.mode==='journey'){toast('You found it. The cerebellum sits behind the brainstem, below the occipital lobes.');}narrate();}
function openExplore(){state.mode='explore';state.paused=true;state.selected=null;state.special=null;state.deep=false;state.search='';audio.cancel();world?.setView('brain',[]);if(world){world.playing=true;world.rotating=true;}render();}
function render(){
 if(!state.started){renderIntro();return;}if(state.intro)return;
 const s=activeScene(),ch=CHAPTERS[state.c];labelCache='';
 $('#interface').innerHTML=`
 <header class="topbar"><button class="wordmark" data-action="chapters" aria-label="Open journey chapters">INSIDE THE HUMAN BRAIN<span>AN INTERACTIVE JOURNEY</span></button><nav class="modes" aria-label="Experience mode"><button data-action="journey" class="${state.mode==='journey'?'active':''}" aria-pressed="${state.mode==='journey'}">Journey</button><button data-action="explore" class="${state.mode==='explore'?'active':''}" aria-pressed="${state.mode==='explore'}">Explore</button></nav><div class="top-actions">${btn('sound',`<span class="sound-label">${audio.enabled?'Sound on':'Sound off'}</span>`,audio.enabled?'sound':'mute','icon-button',`aria-label="${audio.enabled?'Turn sound off':'Turn sound on'}" title="${audio.enabled?'Sound on':'Sound off'}"`)}${btn('narration','', 'voice','icon-button optional-top',`aria-label="Toggle voice narration" title="Narration ${audio.narration?'on':'off'}" aria-pressed="${audio.narration}"`)}${btn('captions','','cc','icon-button optional-top',`aria-label="Toggle captions" title="Captions ${state.captions?'on':'off'}" aria-pressed="${state.captions}"`)}<i class="divider"></i>${btn('chapters','','menu','icon-button','aria-label="Open chapters and settings" title="Chapters and settings"')}</div></header>
 <div id="model-labels" class="model-labels"></div>
 <div class="model-caption"><b>${world?.groupMode(world.view)==='brain'?'HUMAN BRAIN':'CELLULAR WORLD'}</b><br>${['neuron','synapse','glia','circuit'].includes(world?.view)?'SCHEMATIC · SCALE ENLARGED': 'RESEARCH ANATOMY + TEACHING MODELS'}</div>
 <div class="floating-tools">${btn('surprise','Surprise me')}${btn('whatifs','What if?')}</div>
 <section class="story" aria-label="${state.selected?'Selected structure':'Current scene'}">${storyContent(s,ch)}</section>
 <div class="orientation"><strong>Drag to rotate · Scroll to zoom</strong><br>Right-drag to pan · Select to discover</div>
 ${toolbar()}
 ${state.viewMenu?viewMenu():''}
 <footer class="bottom"><div class="play-row"><div class="play-left">${state.mode==='journey'?btn('play',`<span class="play-ring">${icon(state.paused?'play':'pause')}</span>${state.paused?'Play journey':'Pause journey'}`,'','play-toggle'):`<span class="chapter-caption">The model is yours to explore.</span>`}<span class="play-status" id="play-status">${String(state.c+1).padStart(2,'0')} / 10</span></div><div class="play-right">${state.mode==='journey'?btn('previous','','prev','icon-button','aria-label="Previous scene"'):btn('index','All structures','','text-button')}${state.mode==='journey'?btn('next',state.c===9&&state.s===3?'Explore':'Next scene','next','next-button'):btn('journey','Back to journey','next','next-button')}</div></div><nav class="progress-rail" aria-label="Journey chapters">${CHAPTERS.map((x,i)=>`<button class="chapter-tick ${i===state.c?'current':''}" data-chapter="${i}" title="${String(i+1).padStart(2,'0')} · ${esc(x.name)}" aria-label="Chapter ${i+1}: ${esc(x.name)}" ${i===state.c?'aria-current="step"':''} style="--fill:${i<state.c?100:0}%"></button>`).join('')}</nav><div class="rail-labels"><span>${String(state.c+1).padStart(2,'0')} &nbsp; ${esc(ch.name.toUpperCase())}</span>${btn('sources','THE SCIENCE & SOURCES')}</div></footer>
 ${worldError?'<div class="no-webgl">The 3D view could not start on this device. The full chapter text, experiments, and structure index remain available. Try a browser with WebGL enabled to explore the model.</div>':''}
 <dialog id="dialog" aria-labelledby="dialog-title"></dialog>`;
 initDemo();updateProgress();
}
function storyContent(s,ch){
 let out='';if(state.special)out+=btn('return','← Return to the journey','','return-link');
 if(state.mode==='explore'&&!state.special){out+=`<div class="explore-search">${icon('search')}<input id="system-search" type="search" autocomplete="off" placeholder="Memory, vision, language…" value="${esc(state.search)}" aria-label="Search brain systems"><div class="search-suggestions">${['memory','vision','language','movement','attention','emotion','sleep'].map(x=>`<button data-search="${x}">${x}</button>`).join('')}</div><div class="search-results" id="search-results"></div></div>`;}
 if(state.selected){const d=STRUCTURES[state.selected];return out+`${btn('unselect','← Back to the whole','','return-link')}<div class="eyebrow">${['cerebellum','hypothalamus','brainstem','midbrain','pons','medulla','spinal','callosum'].includes(state.selected)?'ANATOMICAL TEACHING MODEL':'ANATOMY IN CONTEXT'}</div><h1>${esc(d.name)}</h1><div class="detail-line"><small>WHERE IS IT?</small><p>${esc(d.where)}</p></div><div class="detail-line"><small>WHAT DOES IT DO?</small><p>${esc(d.does)}</p></div><div class="detail-line"><small>WHY SHOULD I CARE?</small><p>${esc(d.care)}</p></div><div class="detail-actions">${btn('take','Take me there')}${btn('function','Show what it does')}${btn('isolate',world?.isolated?'Restore context':'Isolate')}</div>${deepContent(d.deep,d.source)}`;}
 if(state.mode==='explore'&&!state.special){return out+`<div class="eyebrow">FOLLOW YOUR CURIOSITY</div><h1 id="explore-title">Where will\nyou go?</h1><p class="hook" id="explore-hook">Select a structure. Follow a connection. Make something happen.</p><p class="explanation" id="explore-explanation">Search an experience to illuminate several systems together. Turn on X-ray to discover what is hidden beneath the cortex.</p><div class="detail-actions">${btn('index','Find a structure')}${btn('connections','Show connections')}${btn('xray','Make transparent')}</div>`;}
 const heading=state.special?s.title:(state.s===0?ch.title:s.title);
 out+=`<div class="eyebrow">${state.special?.type==='whatif'?'A CAREFUL THOUGHT EXPERIMENT':state.special?'A DIFFERENT WAY TO SEE':`CHAPTER ${String(state.c+1).padStart(2,'0')} · ${esc(ch.subtitle)}`}</div><div class="scene-counter">${state.s+1} / ${ch.scenes.length} SCENES</div><h1>${esc(heading)}</h1><p class="hook">${esc(s.hook)}</p>${state.captions?`<p class="explanation">${esc(s.text)}</p>`:''}${s.task?`<p class="scene-task">${icon('focus')}${esc(s.task)}</p>`:''}${renderDemo(s)}${deepContent(s.deeper||(s.demo==='transmitters'?TRANSMITTERS.find(x=>x.id===state.transmitter).detail:defaultDeep(s)),s.demo==='transmitters'?TRANSMITTERS.find(x=>x.id===state.transmitter).source:s.source,s.evidence)}`;
 return out;
}
function defaultDeep(s){if(s.focus?.[0]&&STRUCTURES[s.focus[0]])return STRUCTURES[s.focus[0]].deep;if(s.view==='synapse')return 'This is one chemical synapse. Electrical synapses also exist. Neurotransmitter receptors, cellular state, and circuit architecture determine the response; the animation does not measure a real person’s brain.';if(s.view==='glia')return 'Different glial types have distinct developmental origins and functions. Ratios of glia to neurons vary widely by region; the old claim of ten glial cells per neuron across the human brain is not reliable.';return 'The highlights are explanatory models of selected systems. Real activity is parallel, recurrent, and far more complex. This experience cannot infer what your own neurons are doing.';}
function deepContent(text,source,evidence='We know'){return`${btn('deeper',state.deep?'Less detail ↑':'Go deeper ↓','','deeper-link')}<div class="evidence-tag">${esc(evidence)}</div>${state.deep?`<div class="deep-copy">${esc(text)}${sourceLink(source)}${btn('sources','About the anatomy & all sources','','deeper-link')}</div>`:''}`;}
function toolbar(){return `<nav class="toolbar" aria-label="3D view controls">${[['rotate','Rotate automatically','rotate'],['zoom','Zoom in','zoom'],['out','Zoom out','minus'],['explode','Separate hemispheres','explode'],['xray','Make the cortex transparent','xray'],['connections','Show connections','connections'],['reset','Reset view','reset']].map(([a,l,i])=>btn(a,'',i,`${a==='xray'&&world?.xray||a==='explode'&&world?.exploded||a==='connections'&&world?.connections?'active':''}`,`aria-label="${l}" title="${l}"`)).join('')}<span class="tool-break"></span>${btn('view-more','View','','view-more','aria-label="More view controls"')}</nav>`;}
function viewMenu(){return `<div class="view-popover" role="group" aria-label="More view controls">${[['pan','Pan with one finger'],['section','Cortical cutaway'],['isolate','Isolate selection'],['labels','Toggle labels'],['reset','Reset view'],['narration',`Narration ${audio.narration?'on':'off'}`],['captions',`Captions ${state.captions?'on':'off'}`]].map(([a,l])=>btn(a,l)).join('')}</div>`;}

function renderDemo(s){const type=s.demo;if(!type)return'';let html='';const canvas=(id='demo-canvas')=>`<canvas id="${id}" width="640" height="236" role="img" aria-label="${esc(type)} interactive illustration"></canvas>`;
 switch(type){
 case'folds':html=`<div class="demo-row">${btn('gyrus','Find a gyrus')}${btn('sulcus','Find a sulcus')}</div><p class="demo-note">Raised ridges and the grooves between them.</p>`;break;
 case'tissue':html=`<div class="demo-row">${btn('section','Toggle cutaway')}${btn('white','Highlight white matter')}</div><p class="demo-note">The cutaway clips the surface to reveal inner structures; it is not an MRI slice.</p>`;break;
 case'illusion':html=canvas()+`<div class="demo-row">${btn('illusion',state.illusion?'Restore context':'Reveal the identical color','','primary-demo')}</div><p class="demo-note">Simultaneous brightness contrast. Center pixels: #909090.</p>`;break;
 case'neurons':html=canvas()+`<div class="demo-readout">≈ 69 billion in the cerebellum</div><p class="demo-note">80 gold dots : 20 pale dots · Approximate proportions, not cells or intelligence.</p>`;break;
 case'energy':html=canvas()+`<p class="demo-note">Adult approximate averages at rest. Proportions change with age and state.</p>`;break;
 case'homunculus':html=canvas()+`<p class="demo-note">Sensory homunculus: a schematic map along cortex, not a person’s shape. Areas are illustrative, not measured.</p>`;break;
 case'inhibition':html=`<div class="demo-readout" id="go-message">A moment of control.</div><div class="demo-row">${btn('go','Try WAIT / GO','','primary-demo','id="go-button"')}</div><p class="demo-note">A discovery exercise—not a measure of your brain health or ability.</p>`;break;
 case'practice':html=`<div class="mini-heading">Type the sequence A · S · D · F</div><div class="practice-keys">${['A','S','D','F'].map((k,i)=>`<button data-key="${i}" class="${state.practice===i?'active':''}">${k}</button>`).join('')}</div><div class="demo-readout" id="practice-note">${state.practiceCount?`${state.practiceCount} sequences completed. Notice the anticipation.`:'Feel the sequence become familiar.'}</div>`;break;
 case'catch':html=canvas()+`<div class="demo-row">${btn('catch','Launch the ball','','primary-demo')}</div><p class="demo-note" id="catch-note">Drag across the scene to position the catcher. Compare prediction with the result.</p>`;break;
 case'context':html=`<div class="demo-readout">The same sudden crash.</div><div class="demo-row">${btn('context-home','At home alone','',''+(!state.context?'active':''))}${btn('context-film','On a film set','',''+(state.context?'active':''))}</div><p class="demo-note">${state.context?'Knowing the sound was staged may change how it is interpreted.':'An unexpected sound at home may feel more uncertain.'} Responses vary with the person and situation.</p>`;break;
 case'body':html=canvas()+`<div class="demo-row">${btn('body-heat','Add heat')}${btn('body-thirst','Lose water')}${btn('body-reset','Restore baseline')}</div><p class="demo-note">Selected regulatory responses, shown conceptually.</p>`;break;
 case'memory':html=canvas()+`<div class="demo-row">${btn('memory-cue','Cue: your first day','','primary-demo')}</div><p class="demo-note">The links represent distributed interactions, not the contents of your memory.</p>`;break;
 case'hearing':html=canvas()+`<div class="demo-row">${btn('listen','Hear a voice','','primary-demo')}</div><p class="demo-note">Watch auditory pathways while a device voice says “Someone is calling your name.”</p>`;break;
 case'neuron':html=`<div class="demo-readout" id="neuron-part">Select a labeled part of the neuron.</div><div class="demo-row">${btn('signal','Send an action potential','','primary-demo')}</div><p class="demo-note">Schematic multipolar neuron. Cell shape and proportions vary.</p>`;break;
 case'potential':case'myelin':html=canvas()+`<div class="demo-row">${btn('signal','Trigger signal','','primary-demo')}${btn('speed-normal','Normal speed','',state.speed===1?'active':'')}${btn('speed-slow','1,000× slower','',state.speed===1000?'active':'')}</div>${type==='myelin'?`<div class="demo-row">${btn('myelin-on','Myelin on','',state.myelin?'active':'')}${btn('myelin-off','Myelin off','',!state.myelin?'active':'')}</div>`:''}<p class="demo-readout" id="signal-note">The membrane changes state along the axon.</p><p class="demo-note">Representative 30 cm path: ${state.myelin?'50 m/s → 6 ms':'10 m/s → 30 ms'}. Chosen example speeds; not a universal myelin multiplier. Geometry is not to scale.</p>`;break;
 case'synapse':case'transmitters':{const nt=TRANSMITTERS.find(x=>x.id===state.transmitter);html=`${type==='transmitters'?`<div class="network-choices">${TRANSMITTERS.map(x=>`<button data-nt="${x.id}" class="${x.id===state.transmitter?'active':''}">${x.name}</button>`).join('')}</div><div class="demo-readout">${esc(nt.receptor)}</div><p class="demo-note">${esc(nt.effect)}</p>${nt.id==='dopamine'?`<div class="demo-row">${btn('d1','D1-like · cAMP ↑','',state.receptor==='d1'?'active':'')}${btn('d2','D2-like · cAMP ↓','',state.receptor==='d2'?'active':'')}</div>`:''}`:''}<div class="demo-row">${btn('release','Release a signal','','primary-demo')}${btn('freeze','Pause / resume')}</div><div class="demo-readout" id="synapse-phase">Ready at the presynaptic terminal.</div><p class="demo-note">A chemical synapse · Anatomy enlarged · Timing illustrative</p>`;break;}
 case'glia':html=`<div class="network-choices">${[['astrocyte','Astrocytes'],['oligodendrocyte','Oligodendrocytes'],['microglia','Microglia']].map(([id,name])=>`<button data-glia="${id}" class="${(s.glial||world?.glial)===id?'active':''}">${name}</button>`).join('')}</div><p class="demo-note">Distinct cell types, simplified shapes. Neurons depend on this community.</p>`;break;
 case'scale':html=`<div class="demo-readout" id="scale-label">One synapse → one neuron → local circuit → network → brain → human</div><label class="demo-note" for="scale-slider">Travel through six scales</label><input id="scale-slider" type="range" min="0" max="5" step="1" value="${state.scale}" aria-valuetext="${['Synapse','Neuron','Circuit','Network','Brain','Human'][state.scale]}"><p class="demo-note">Scale transitions are conceptual; the scenes do not share one physical scale.</p>`;break;
 case'networks':html=`<div class="network-choices">${Object.entries(NETWORKS).map(([id,n])=>`<button data-network="${id}" class="${state.network===id?'active':''}">${n.name}</button>`).join('')}</div><div class="demo-readout" id="network-hook">${NETWORKS[state.network].hook}</div><p class="demo-note" id="network-text">${NETWORKS[state.network].text}</p>`;break;
 case'evidence':html=`<div class="evidence-line"><b>WE KNOW</b>Cells communicate electrically and chemically.</div><div class="evidence-line"><b>OUR BEST MODEL</b>Dynamic interactions help explain cognition.</div><div class="evidence-line"><b>WE DON’T YET KNOW</b>A complete account of subjective experience.</div>`;break;
 case'experience':{const e=EXPERIENCES[s.experience];html=`<div class="network-choices">${Object.entries(EXPERIENCES).map(([id,x])=>`<button data-experience="${id}" class="${s.experience===id?'active':''}">${x.name}</button>`).join('')}</div>${s.experience==='see'?`<div class="face-cue"><span class="face-frame"><img src="assets/face-stimulus.jpg" alt="Portrait of Mae Jemison, photographed by NASA" width="120" height="135"></span><div><p>Light becomes a face.<br>A face becomes a person.</p><a href="https://commons.wikimedia.org/wiki/File:Mae-jemison.jpg" target="_blank" rel="noopener">Mae Jemison · NASA photo ↗</a></div></div>`:''}${s.experience==='hear'?'<div class="demo-row"><input class="small-input" id="your-name" aria-label="A name to hear" placeholder="Your first name" maxlength="30"><button data-action="name">Hear your name</button></div>':''}${s.experience==='think'?`<div class="demo-readout">27 + 16 = <span id="sum-answer">?</span></div>`:''}<div class="demo-row">${btn('experience-play',s.experience==='think'?'Reveal the reasoning':'Watch the experience','','primary-demo')}</div><div class="path-steps">${e.steps.map((x,i)=>`<button data-step="${i}" class="${state.pathStep===i?'active':''}">${esc(x)}</button>`).join('')}</div><p class="demo-note">${esc(e.text)}</p>`;break;}
 case'sleep':html=canvas()+`<div class="demo-row">${[['wake','Awake'],['nrem','Deep NREM'],['rem','REM']].map(([id,n])=>`<button data-sleep="${id}" class="${state.sleep===id?'active':''}">${n}</button>`).join('')}</div><p class="demo-note" id="sleep-note">Illustrative EEG-like trace; not a clinical recording. A typical night cycles through states.</p>`;break;
 case'whatif':html=`<div class="demo-row">${btn('whatif-normal','Show connected system','','active')}${btn('whatif-change','Highlight the disruption')}</div><p class="demo-note">An explanation of affected relationships—not a simulation of someone’s lived condition.</p>`;break;
 case'finale':html=`<div class="demo-row">${btn('finale','Replay the final zoom')}${btn('explore','Explore your brain','next','primary-demo')}</div>`;break;
 }
 return `<div class="demo" data-demo="${type}">${html}</div>`;
}

function initDemo(){demoAnimation=0;const s=activeScene();if(s.demo==='catch'){const canvas=$('#demo-canvas');canvas?.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();state.catcher=Math.max(.06,Math.min(.94,(e.clientX-r.left)/r.width));});canvas?.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();state.catcher=Math.max(.06,Math.min(.94,(e.clientX-r.left)/r.width));canvas.setPointerCapture(e.pointerId);});}if(state.search)searchSystems(state.search,false);}
function updateProgress(){const tick=$('.chapter-tick.current');if(tick)tick.style.setProperty('--fill',`${(state.s+Math.min(1,state.elapsed/current().duration))/CHAPTERS[state.c].scenes.length*100}%`);const status=$('#play-status');if(status)status.textContent=`${String(state.c+1).padStart(2,'0')} / 10 · SCENE ${state.s+1} OF ${CHAPTERS[state.c].scenes.length}`;}

function showDialog(title,content){const d=$('#dialog');if(!d)return;state.wasPaused=state.paused;pause(true);if(world)world.playing=false;d.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${esc(title)}</h2><button data-action="close-dialog" aria-label="Close dialog">×</button></div>${content}`;d.showModal();d.oncancel=()=>closeDialog();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}},{once:false});}
function closeDialog(){const d=$('#dialog');d?.close();if(state.mode==='journey')pause(state.wasPaused??false);else if(world)world.playing=true;}
function showChapters(){showDialog('Choose your chapter',`<p class="dialog-intro">Follow the whole journey, or enter at any scale. The full guided film runs about 22 minutes; take longer to explore.</p><div class="chapter-list">${CHAPTERS.map((c,i)=>`<button data-chapter="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span>${esc(c.name)}<small>${c.scenes.length} scenes${state.visited.has(i)?' · visited':''}</small></button>`).join('')}</div><div class="demo-row">${btn('replay-intro','Replay opening')}${btn('narration',`Narration: ${audio.narration?'on':'off'}`)}${btn('captions',`Captions: ${state.captions?'on':'off'}`)}${btn('index','All structures')}</div><p class="demo-note">Space: play/pause · ← / →: previous/next scene · Esc: close · All controls support touch.</p>`);}
function showSources(){showDialog('The science behind the journey',`<p class="dialog-intro">An educational model for high school through undergraduate study. Read the references alongside each scene to follow the evidence.</p><div class="model-note"><strong>What you are seeing.</strong> The cerebral cortex is the MRI-derived FreeSurfer fsaverage5 research template with Desikan–Killiany labels. The hippocampi, amygdalae, thalami, basal ganglia components, and lateral ventricles use spatially compatible ENIGMA meshes. These are research templates, not an individual’s scan.<br><br>The cerebellum, brainstem, spinal cord, hypothalamus, corpus callosum, body, neurons, and molecular scenes are simplified teaching models. Cortical lobe groupings have approximate educational boundaries. A cutaway removes part of the surface; it does not display a tissue section.<br><br>Colors, animated pathways, network boundaries, and light represent selected relationships or changing states. They are not observed activity, literal light, a complete wiring map, or diagnostic evidence. Surface vessels, where shown, are schematic. Cellular geometry and timing are enlarged or slowed as labeled.</div><div class="model-note"><strong>Evidence has different levels.</strong><br>“We know” means strong evidence supports the central mechanism. “Our best model” identifies useful but incomplete interpretations. “We don’t yet know” marks an open question. Functional networks overlap and vary across people, tasks, and measurement methods.</div><div class="source-list">${Object.keys(SOURCES).map(sourceLink).join('')}<a href="assets/THIRD-PARTY-NOTICES.txt" target="_blank" rel="noopener">Anatomical data provenance, transformations & license notices ↗</a><a href="assets/THREE-LICENSE.txt" target="_blank" rel="noopener">Three.js license ↗</a></div><p class="demo-note">Scientific explanations are educational, not medical assessments. Thought experiments describe variable effects carefully and do not diagnose anyone.</p>`);}
function showIndex(){showDialog('A brain, in context',`<p class="dialog-intro">Choose a structure to locate it in the model. The left and right sides refer to the person’s anatomy.</p><div class="structure-index">${Object.entries(STRUCTURES).map(([id,d])=>`<button data-structure="${id}">${d.name}</button>`).join('')}</div>`);}
function showWhatifs(){showDialog('What if a connection changes?',`<p class="dialog-intro">Careful thought experiments can reveal how systems depend on one another. The effects of neurological changes vary across people and circumstances.</p><div class="chapter-list">${WHATIFS.map((x,i)=>`<button data-whatif="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span>${esc(x.title)}</button>`).join('')}</div>`);}
function special(type,index){state.special={type,index};state.selected=null;state.paused=true;state.deep=false;const s=activeScene();configureWorld(s);if(world){world.playing=true;if(type==='whatif')world.setConnections(true,s.id==='split'?'callosal':undefined);}render();narrate();}
function searchSystems(q,update=true){state.search=q;const normalized=q.toLowerCase().trim();let ids=SEARCH_SYSTEMS[normalized]||Object.entries(STRUCTURES).filter(([id,d])=>(d.name+' '+d.does+' '+d.care).toLowerCase().includes(normalized)).map(([id])=>id);if(!normalized)ids=[];const result=$('#search-results');if(result)result.innerHTML=ids.length?ids.map(id=>`<button data-structure="${id}">${STRUCTURES[id].name}</button>`).join(''):normalized?'<p class="demo-note">No match yet. Try memory, language, sleep, or a structure’s name.</p>':'';
 if(update&&world){if(world.groupMode(world.view)!=='brain')world.setView('xray',ids);world.xray=true;world.setFocus(ids);world.setConnections(ids.length>0);}
 const title=$('#explore-title');if(title)title.textContent=normalized&&ids.length?`Follow ${normalized}.`:'Where will you go?';const hook=$('#explore-hook');if(hook)hook.textContent=ids.length?`${ids.length} related structures illuminated together.`:'Select a structure. Follow a connection. Make something happen.';const expl=$('#explore-explanation');if(expl)expl.textContent=ids.length?'A function is a collaboration. Select a highlighted structure to locate it, then follow its connections. These are selected contributors, not an exhaustive list.':'Search an experience to illuminate several systems together. Turn on X-ray to discover what is hidden beneath the cortex.';
}

document.addEventListener('click',async e=>{
 const el=e.target.closest('button');if(!el)return;
 if(el.dataset.chapter!==undefined){$('#dialog')?.close();enterJourney(Number(el.dataset.chapter),0);return;}
 if(el.dataset.structure){$('#dialog')?.close();if(world&&world.groupMode(world.view)!=='brain')world.setView('brain',[]);selectStructure(el.dataset.structure);return;}
 if(el.dataset.neuron){showNeuron(el.dataset.neuron);return;}
 if(el.dataset.whatif!==undefined){$('#dialog')?.close();special('whatif',Number(el.dataset.whatif));return;}
 if(el.dataset.search){state.selected=null;render();const input=$('#system-search');if(input)input.value=el.dataset.search;searchSystems(el.dataset.search);return;}
 if(el.dataset.nt){state.transmitter=el.dataset.nt;world?.setTransmitter(TRANSMITTERS.find(x=>x.id===state.transmitter).color);render();return;}
 if(el.dataset.glia){world?.setGlia(el.dataset.glia);const map={astrocyte:0,oligodendrocyte:1,microglia:2};loadScene(6,map[el.dataset.glia]);return;}
 if(el.dataset.network){state.network=el.dataset.network;world?.setFocus(NETWORKS[state.network].nodes);world?.setConnections(true,state.network);render();return;}
 if(el.dataset.sleep){state.sleep=el.dataset.sleep;updateSleep();render();return;}
 if(el.dataset.experience){loadScene(8,Object.keys(EXPERIENCES).indexOf(el.dataset.experience));return;}
 if(el.dataset.step!==undefined){state.pathStep=Number(el.dataset.step);state.pathStart=-100;updatePath();return;}
 if(el.dataset.key!==undefined){practice(Number(el.dataset.key));return;}
 const a=el.dataset.action;if(!a)return;
 if(el.closest('.demo')&&!['explore','finale'].includes(a)){state.paused=true;audio.cancel();if(world)world.playing=true;const pb=$('[data-action="play"]');if(pb)pb.innerHTML=`<span class="play-ring">${icon('play')}</span>Play journey`;}
 switch(a){
 case'begin':startIntro(true);break;case'begin-silent':startIntro(false);break;case'skip-intro':enterJourney(0,0);break;case'replay-intro':$('#dialog')?.close();startIntro(audio.enabled);break;
 case'journey':state.mode='journey';state.special=null;state.selected=null;loadScene(state.c,state.s);break;case'explore':openExplore();break;
 case'play':if(state.selected){state.selected=null;configureWorld(current());render();}pause();break;case'next':next();break;case'previous':prev();break;
 case'sound':await audio.toggle();if(!state.intro)render();else el.innerHTML=icon(audio.enabled?'sound':'mute');if(audio.enabled&&!state.intro)narrate();break;
 case'narration':audio.narration=!audio.narration;if(!audio.narration)audio.cancel();else narrate();if($('#dialog')?.open)showChapters();else render();toast(audio.available?`Device narration ${audio.narration?'on':'off'}.`:'Voice narration is unavailable in this browser. Captions are available throughout.');break;
 case'captions':state.captions=!state.captions;$('#dialog')?.close();render();break;
 case'chapters':showChapters();break;case'sources':showSources();break;case'index':showIndex();break;case'whatifs':showWhatifs();break;case'close-dialog':closeDialog();break;
 case'surprise':state.surprise=(state.surprise+1)%SURPRISES.length;special('surprise',state.surprise);break;case'return':state.special=null;state.selected=null;loadScene(state.c,state.s);break;
 case'deeper':state.deep=!state.deep;render();break;
 case'unselect':state.selected=null;state.deep=false;if(world){world.isolated=false;world.setFocus([]);}if(state.mode==='journey'){state.paused=false;configureWorld(current());}render();break;
 case'take':world?.takeMe(state.selected);break;
 case'function':{const id=state.selected;let found=null;const preferred={hippocampus:[2,2],amygdala:[2,3],basal:[2,4],hypothalamus:[2,5],cerebellum:[2,7],callosum:[3,0],motor:[8,2],spinal:[8,2],temporal:[8,1],occipital:[8,0],frontal:[8,5],parietal:[1,3],ventricles:[2,9]};found=preferred[id];if(!found)for(let c=0;c<CHAPTERS.length;c++){const i=CHAPTERS[c].scenes.findIndex(x=>x.focus.includes(id));if(i>=0){found=[c,i];break;}}state.mode='journey';loadScene(...(found||[0,0]));if(current().demo==='experience')playExperience();break;}
 case'rotate':if(world){world.rotating=!world.rotating;world.playing=true;}toast(world?.rotating?'Slow rotation on.':'Rotation paused. Drag to explore.');break;
 case'zoom':case'out':if(world){world.flight=null;const delta=world.camera.position.clone().sub(world.controls.target);delta.multiplyScalar(a==='zoom'?.8:1.25);world.camera.position.copy(world.controls.target).add(delta);world.controls.update();}break;
 case'pan':if(world){world.panMode=!world.panMode;world.controls.mouseButtons.LEFT=world.panMode?2:0;world.controls.touches.ONE=world.panMode?1:0;toast(world.panMode?'Pan mode: drag the model. Select Pan again to rotate.':'Rotate mode restored.');}break;
 case'explode':if(world){if(world.groupMode(world.view)!=='brain'){toast('Hemisphere separation is available at whole-brain scale.');break;}world.exploded=!world.exploded;}render();break;
 case'xray':if(world){if(world.groupMode(world.view)!=='brain'){toast('X-ray reveals structures at whole-brain scale.');break;}world.xray=!world.xray;world.applyFocus();}render();break;
 case'connections':if(world){if(world.groupMode(world.view)!=='brain'){toast('Connections between regions are visible at whole-brain scale.');break;}world.setConnections(!world.connections);if(world.connections){world.xray=true;world.applyFocus();}}render();break;
 case'section':if(world){world.section=!world.section;world.applyFocus();}render();break;
 case'isolate':if(!world?.focus.length){toast('Select a structure to isolate it while keeping faint anatomical context.');break;}world.isolated=!world.isolated;world.applyFocus();render();break;
 case'reset':world?.setView(activeScene().view||'brain',activeScene().focus||[]);if(world){world.exploded=false;world.xray=false;world.section=false;world.isolated=false;world.rotating=true;world.applyFocus();world.controls.mouseButtons.LEFT=0;world.controls.touches.ONE=0;}state.selected=null;render();break;
 case'view-more':state.viewMenu=!state.viewMenu;render();break;case'labels':state.hideLabels=!state.hideLabels;render();break;
 case'gyrus':world?.takeMe('motor');toast('The precentral gyrus is a ridge. Its neighboring grooves are sulci.');break;case'sulcus':world?.takeMe('parietal');toast('Look between the precentral and postcentral ridges: the central sulcus separates frontal and parietal cortex.');break;case'white':world?.setFocus(['callosum']);if(world){world.xray=true;world.applyFocus();}toast('The corpus callosum is white matter: bundles of axons linking hemispheres.');break;
 case'illusion':state.illusion=!state.illusion;render();break;
 case'context-home':case'context-film':state.context=a==='context-film';world?.setConnections(true,'feel');audio.cue('context');render();break;
 case'body-heat':case'body-thirst':case'body-reset':state.body=a==='body-heat'?'heat':a==='body-thirst'?'thirst':'normal';world?.setConnections(true,'feel');render();break;
 case'memory-cue':state.memoryCue=performance.now();world?.setConnections(true,'remember');audio.cue();break;
 case'listen':await audio.start(true);audio.narration=true;audio.speak('Someone is calling your name.');world?.setConnections(true,'hear');break;
 case'name':{const name=$('#your-name')?.value.trim()||'Alex';await audio.start(true);audio.narration=true;audio.speak(`Hey, ${name}.`);playExperience();break;}
 case'signal':if(world){world.playing=true;world.speed=state.speed;world.trigger();state.signalStart=world.time;}audio.cue();break;
 case'speed-normal':case'speed-slow':state.speed=a==='speed-normal'?1:1000;if(world){world.speed=state.speed;world.playing=true;world.trigger();}render();break;
 case'myelin-on':case'myelin-off':state.myelin=a==='myelin-on';world?.setMyelin(state.myelin);if(world){world.playing=true;world.trigger();}render();break;
 case'release':if(world){world.playing=true;world.trigger();}audio.cue();break;
 case'freeze':if(world){world.playing=!world.playing;toast(world.playing?'Molecular motion resumed.':'Molecular motion paused.');}break;
 case'd1':case'd2':state.receptor=a;if(world){world.setTransmitter(a==='d1'?'#e5b9ca':'#a0a8d1');world.trigger();world.playing=true;}render();toast(a==='d1'?'D1-like receptors typically increase cAMP signaling. This does not directly mean more pleasure.':'D2-like receptors typically reduce cAMP signaling. The circuit’s response depends on its context.');break;
 case'experience-play':playExperience();break;
 case'go':go();break;
 case'catch':state.catchStart=performance.now();state.catchDone=false;break;
 case'whatif-normal':case'whatif-change':if(world){world.setConnections(true,state.special?.index===0?'callosal':undefined);if(a==='whatif-change'){world.pathDots.forEach((d,i)=>{if(i%2===0)d.visible=false;});world.lines.traverse(o=>{if(o.material)o.material.color.set('#cc9090');});}toast(a==='whatif-change'?'Highlighted: selected interactions affected by this change. Effects vary; this is not a clinical simulation.':'Showing selected relationships in the connected system.');}break;
 case'finale':state.finaleStart=performance.now();state.finaleStage=-1;break;
 }
});
document.addEventListener('input',e=>{if(e.target.id==='system-search')searchSystems(e.target.value);if(e.target.id==='scale-slider'){state.scaleStart=0;state.scale=Number(e.target.value);const views=['synapse','neuron','circuit','network','brain','finale'];world?.setView(views[state.scale],[]);if(state.scale===3)world?.setConnections(true,'default');e.target.setAttribute('aria-valuetext',['Synapse','Neuron','Circuit','Network','Brain','Human'][state.scale]);const l=$('#scale-label');if(l)l.textContent=['One synapse','One neuron, many inputs','A local circuit','A functional network','The whole brain','A human being'][state.scale];}});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||$('#dialog')?.open)return;if(!state.started)return;if(state.intro){if(e.key==='Escape')enterJourney(0,0);return;}if(e.code==='Space'){e.preventDefault();pause();}if(e.key==='ArrowRight'){e.preventDefault();next();}if(e.key==='ArrowLeft'){e.preventDefault();prev();}if(activeScene().demo==='practice'&&'asdf'.includes(e.key.toLowerCase())&&e.key.length===1)practice('asdf'.indexOf(e.key.toLowerCase()));});
function showNeuron(id){const part=world?.neuronLabels.find(x=>x.id===id);if(!part)return;const target=$('#neuron-part');if(target)target.textContent=`${part.name}: ${part.description}`;else toast(`${part.name}: ${part.description}`);}
function practice(i){if(state.practice===i){state.practice++;if(state.practice===4){state.practice=0;state.practiceCount++;audio.cue();world?.setConnections(true,'action');}}else toast('Return to the highlighted next key. Repetition and feedback help shape action.');render();}
function go(){const b=$('#go-button'),p=$('#go-message');if(state.goState==='idle'||state.goState==='done'){state.goState='wait';if(b)b.textContent='WAIT';if(p)p.textContent='Hold back until the cue changes.';clearTimeout(state.goTimer);state.goTimer=setTimeout(()=>{state.goState='go';state.goStart=performance.now();const b=$('#go-button'),p=$('#go-message');if(b)b.textContent='GO — tap now';if(p)p.textContent='Your goal changed. Respond.';world?.setConnections(true,'control');},1800+Math.random()*2200);}else if(state.goState==='wait'){clearTimeout(state.goTimer);state.goState='done';if(p)p.textContent='You responded before the GO cue. Notice the urge to act.';if(b)b.textContent='Try again';}else{state.goState='done';if(p)p.textContent=`${Math.round(performance.now()-state.goStart)} ms after the cue. Holding back and acting both recruit interacting systems.`;if(b)b.textContent='Try again';}}
function playExperience(){state.pathStart=performance.now();state.pathStep=0;if(world){world.playing=true;world.setConnections(true,activeScene().experience);}if(activeScene().experience==='think'&&$('#sum-answer'))$('#sum-answer').textContent='43';updatePath();audio.cue();}
function updatePath(){document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===state.pathStep));const exp=EXPERIENCES[activeScene().experience];if(world&&exp){const focus=exp.focus[state.pathStep%exp.focus.length];world.setFocus([focus]);}}
function updateSleep(){if(world){world.rotating=state.sleep==='wake';world.setConnections(true,state.sleep==='rem'?'default':'control');world.renderer.toneMappingExposure=state.sleep==='wake'?1.2:state.sleep==='nrem'?.75:1;}audio.mode='sleep';}

function drawDemo(now){const canvas=$('#demo-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.width,h=canvas.height,t=world?.time??now/1000;ctx.clearRect(0,0,w,h);ctx.font='24px -apple-system, sans-serif';ctx.lineWidth=2;const gold='#d8bd93',muted='#8995a5';const text=(s,x,y,c=muted,size=22)=>{ctx.fillStyle=c;ctx.font=`${size}px -apple-system, sans-serif`;ctx.fillText(s,x,y);};const line=(x,y,x2,y2,c)=>{ctx.strokeStyle=c;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();};const circle=(x,y,r,c)=>{ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=c;ctx.fill();};const type=activeScene().demo;
 if(type==='illusion'){ctx.fillStyle=state.illusion?'#909090':'#34373d';ctx.fillRect(0,10,305,180);ctx.fillStyle=state.illusion?'#909090':'#d7d7d7';ctx.fillRect(325,10,305,180);ctx.fillStyle='#909090';ctx.fillRect(109,58,88,88);ctx.fillRect(434,58,88,88);if(state.illusion)line(145,102,477,102,'#cfc1a7');text(state.illusion?'Same pixels. Context changed.':'Do the center squares look identical?',5,226,gold,21);}
 else if(type==='neurons'){for(let i=0;i<100;i++){const x=18+(i%20)*31,y=26+Math.floor(i/20)*32;circle(x,y,6.5+(i<80?Math.sin(t+i*.1)*.5:0),i<80?gold:'#718398');}text('Cerebellum ≈ 80%',0,220,gold,24);text('Rest ≈ 20%',380,220,muted,22);}
 else if(type==='energy'){text('BODY MASS',0,36,muted,19);text('RESTING ENERGY',0,141,muted,19);for(let row=0;row<2;row++)for(let i=0;i<50;i++){const on=i<(row?10:1);ctx.fillStyle=on?gold:'#25303f';ctx.fillRect(i*12.5,55+row*105,9,36);}text('≈ 2%',540,35,gold,24);text('≈ 20%',530,140,gold,24);}
 else if(type==='homunculus'){const parts=[['Leg',.13],['Trunk',.1],['Arm',.12],['Hand',.26],['Face',.13],['Lips',.26]];let x=0;text('MEDIAL',0,25,muted,18);text('LATERAL',535,25,muted,18);for(const[n,f]of parts){ctx.fillStyle=n==='Hand'||n==='Lips'?'#cfb991':'#637a81';ctx.fillRect(x+2,58,f*w-5,n==='Hand'||n==='Lips'?78:43);text(n,x+6,176,gold,18);x+=f*w;}line(3,204,635,204,'#536170');}
 else if(type==='potential'||type==='myelin'){text('+30 mV',0,28,muted,18);text('−70 mV',0,175,muted,18);text('−80',20,215,muted,17);line(102,176,638,176,'#344353');line(105,25,105,216,'#344353');const points=[[0,.75],[.26,.75],[.33,.62],[.37,.48],[.41,.05],[.46,.2],[.53,.76],[.59,.93],[.68,.85],[.77,.75],[1,.75]];ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(110+x*515,15+y*207):ctx.moveTo(110+x*515,15+y*207));ctx.strokeStyle=gold;ctx.lineWidth=3;ctx.stroke();const p=world?.signalProgress??1;if(p<1){const x=110+p*515;line(x,20,x,213,'#c4d8df');}text('Example voltage trace at one membrane site',118,233,muted,16);}
 else if(type==='memory'){const labels=['PLACE','PERSON','SOUND','FEELING'];const active=state.memoryCue&&(now-state.memoryCue)<11000;for(let i=0;i<4;i++){const a=i/4*Math.PI*2-Math.PI/4,x=320+Math.cos(a)*200,y=112+Math.sin(a)*64;line(320,112,x,y,active?'#8caea7':'#263845');circle(x,y,9,active?'#b6d5c6':'#4b6473');text(labels[i],x-45,y+35,gold,18);}circle(320,112,14,active?'#8cc7b9':'#667b78');text('HIPPOCAMPAL',244,196,muted,17);text('INTERACTIONS',243,220,muted,17);}
 else if(type==='body'){text(state.body==='heat'?'WARMER BODY':state.body==='thirst'?'LESS BODY WATER':'INTERNAL REGULATION',0,31,gold,21);for(let i=0;i<4;i++){const x=70+i*165;circle(x,105,27,i===1?gold:'#597c87');if(i<3){line(x+34,105,x+120,105,'#59656f');const p=(t*.4+i*.2)%1;circle(x+35+p*80,105,4,gold);}}['Sensors','Brain','Response','Feedback'].forEach((s,i)=>text(s,28+i*165,161,muted,18));text(state.body==='heat'?'Sweating + altered skin blood flow help shed heat.':state.body==='thirst'?'Thirst and hormonal responses help conserve water.':'Signals help keep the body within workable ranges.',0,221,gold,19);}
 else if(type==='hearing'||type==='sleep'){const sleep=type==='sleep',mode=state.sleep;const amp=sleep&&mode==='nrem'?63:21,freq=sleep&&mode==='nrem'?1.6:9;ctx.strokeStyle=sleep&&mode==='rem'?'#c3b1d2':gold;ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<w;x++){const q=x/w*8+t;const y=110+Math.sin(q*freq)*amp+Math.sin(q*17)*8+Math.sin(q*31)*4;if(x)ctx.lineTo(x,y);else ctx.moveTo(x,y);}ctx.stroke();text(sleep?mode==='wake'?'AWAKE · faster, lower-amplitude pattern':mode==='nrem'?'DEEP NREM · prominent slow waves':'REM · relatively wake-like activity':'Sound pressure changes → neural signals',0,221,muted,19);}
 else if(type==='catch'){const elapsed=(now-state.catchStart)/1000,active=elapsed>=0&&elapsed<2.6;const p=Math.min(1,Math.max(0,elapsed/2.6));const x=70+p*470,y=28+170*p*p;line(0,213,640,213,'#364351');const cx=state.catcher*640;ctx.strokeStyle=gold;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx-35,185);ctx.lineTo(cx-35,210);ctx.lineTo(cx+35,210);ctx.lineTo(cx+35,185);ctx.stroke();if(active){circle(x,y,10,'#d7bc91');for(let i=0;i<8;i++){const q=i/8;circle(70+q*470,28+170*q*q,2,'#435462');}}else circle(70,28,10,'#d7bc91');if(elapsed>=2.6&&!state.catchDone&&state.catchStart>0){state.catchDone=true;const error=Math.abs(cx-540);$('#catch-note').textContent=error<40?'Caught. Visual prediction and sensory feedback can guide the adjustment.':`The ball landed ${Math.round(error)} illustrated units away. Compare the predicted and actual position, then try again.`;world?.setConnections(true,'action');}}
}
function tick(now){const dt=Math.min((now-previous)/1000,.1);previous=now;if(state.intro)tickIntro(now);else if(state.started){if(!state.paused&&!state.selected&&!state.special&&state.mode==='journey'&&!document.hidden&&!$('#dialog')?.open){state.elapsed+=dt;if(state.elapsed>=current().duration&&(!audio.enabled||!audio.narration||!audio.available||!speechSynthesis.speaking||state.elapsed>90))next();}if(uiFrame++%6===0)updateProgress();if(uiFrame%2===0)drawDemo(now);
  if(state.pathStart>0){const exp=EXPERIENCES[activeScene().experience];if(exp){const step=Math.min(exp.steps.length-1,Math.floor((now-state.pathStart)/1700));if(step!==state.pathStep){state.pathStep=step;updatePath();}}}
  const sn=$('#signal-note');if(sn&&world){const duration=(state.myelin?.006:.03)*state.speed,p=world.signalProgress;sn.textContent=p<1?state.speed===1000?`${(p*duration).toFixed(1)} s on screen = ${(p*duration).toFixed(1)} ms in the example`:'Signal in progress…':world.signalStart>-10?`Completed: ${state.myelin?6:30} ms biological travel time in this example.`:'Trigger a signal to follow the changing membrane.';}
  const sp=$('#synapse-phase');if(sp&&world){const p=world.synapseProgress;sp.textContent=p>=1?'Ready to release again.':p<.16?'1 · Calcium enters the terminal':p<.3?'2 · Vesicle fusion and release':p<.58?'3 · Neurotransmitter diffuses across the cleft':p<.78?'4 · Receptor binding changes cellular signaling':'5 · Molecules unbind and are cleared';}
  if(state.scaleStart&&activeScene().demo==='scale'){const stage=Math.min(5,Math.floor((now-state.scaleStart)/3900));if(stage!==state.scaleStage){state.scaleStage=stage;state.scale=stage;world?.setView(['synapse','neuron','circuit','network','brain','finale'][stage],[]);if(stage===3)world?.setConnections(true,'default');const slider=$('#scale-slider');if(slider)slider.value=String(stage);const label=$('#scale-label');if(label)label.textContent=['One synapse','One neuron, many inputs','A local circuit','A functional network','The whole brain','A human being'][stage];}}
  if(activeScene().demo==='finale'&&!state.finaleStart){state.finaleStart=now;state.finaleStage=-1;}if(state.finaleStart&&activeScene().demo==='finale'){const views=['synapse','neuron','circuit','network','brain','finale'];const stage=Math.min(5,Math.floor((now-state.finaleStart)/4200));if(stage!==state.finaleStage){state.finaleStage=stage;world?.setView(views[stage],[]);if(stage===3)world?.setConnections(true,'default');}}
 }requestAnimationFrame(tick);}
function updateLabels(labels){const target=$('#model-labels');if(!target||state.hideLabels)return;if(state.intro)return;const chosen=labels.filter(l=>l.visible).filter(l=>innerWidth<850?l.y<innerHeight*.39&&l.y>125:l.x>innerWidth*.35&&l.y>130&&l.y<innerHeight-200);const unique=chosen.filter((l,i)=>chosen.findIndex(x=>x.name===l.name)===i);const key=unique.map(l=>l.id||l.name).join(',');if(key!==labelCache){target.innerHTML=unique.map(l=>`<button class="anatomy-label" ${l.id?(world?.view==='neuron'?`data-neuron="${l.id}"`:`data-structure="${l.id}"`):'tabindex="-1"'}>${esc(l.name)}</button>`).join('');labelCache=key;}Array.from(target.children).forEach((e,i)=>{e.style.left=`${unique[i].x}px`;e.style.top=`${unique[i].y}px`;});}

async function init(){
 try{world=new BrainWorld($('#scene'),{select:selectStructure,neuron:showNeuron,labels:updateLabels,interact:()=>{if(state.started&&!state.intro){state.paused=true;audio.cancel();const b=$('[data-action="play"]');if(b)b.innerHTML=`<span class="play-ring">${icon('play')}</span>Play journey`;}}});await world.load();}
 catch(e){worldError=true;console.error('Brain scene unavailable:',e);if(world){world.renderer?.domElement.remove();cancelAnimationFrame(world.frameId);}world=null;}
 const loading=$('#loading');loading.style.opacity='0';setTimeout(()=>loading.remove(),700);renderIntro();requestAnimationFrame(tick);
}
init();

