export const SOURCES = {
 basics: ['NINDS · Know your brain', 'https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-know-your-brain'],
 sleep: ['NINDS · Understanding sleep', 'https://www.ninds.nih.gov/health-information/public-education/brain-basics/brain-basics-understanding-sleep'],
 neurons: ['Purves et al. · Electrical signals', 'https://www.ncbi.nlm.nih.gov/books/NBK10844/'],
 synapse: ['Purves et al. · Calcium and transmitter release', 'https://www.ncbi.nlm.nih.gov/books/NBK11125/'],
 glia: ['Ludwig & Das · Glial cells', 'https://www.ncbi.nlm.nih.gov/books/NBK441945/'],
 numbers: ['Herculano-Houzel · The human brain in numbers', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2776484/'],
 visual: ['NCBI Bookshelf · Visual pathways', 'https://www.ncbi.nlm.nih.gov/books/NBK553189/'],
 auditory: ['NCBI Bookshelf · Auditory pathways', 'https://www.ncbi.nlm.nih.gov/books/NBK532311/'],
 basal: ['Purves et al. · Basal ganglia circuits', 'https://www.ncbi.nlm.nih.gov/books/NBK10860/'],
 cerebellum: ['Purves et al. · Cerebellar coordination', 'https://www.ncbi.nlm.nih.gov/books/NBK11043/'],
 hypothalamus: ['UTHealth · Hypothalamic organization', 'https://nba.uth.tmc.edu/neuroscience/m/s4/chapter01.html'],
 executive: ['UTHealth · Association and executive processing', 'https://nba.uth.tmc.edu/neuroscience/m/s4/chapter09.html'],
 laterality: ['Nielsen et al. · Testing the left/right brain hypothesis', 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0071275'],
 parkinson: ['NINDS · Parkinson’s disease', 'https://www.ninds.nih.gov/health-information/disorders/parkinsons-disease'],
 memory: ['Squire & Wixted · The cognitive neuroscience of human memory', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3192650/'],
 amygdala: ['Janak & Tye · From circuits to behaviour in the amygdala', 'https://www.nature.com/articles/nature14188'],
 networks: ['Yeo et al. · Organization of the human cerebral cortex', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3174820/'],
 thalamus: ['Halassa & Kastner · Thalamic functions in distributed cognitive control', 'https://www.nature.com/articles/s41593-017-0020-1'],
 transmitters: ['Purves et al. · Neurotransmitter receptors and membrane permeability', 'https://www.ncbi.nlm.nih.gov/books/NBK10951/'],
 plasticity: ['UTHealth · Learning and memory', 'https://nba.uth.tmc.edu/neuroscience/m/s4/chapter07.html'],
 somatic: ['UTHealth · Somatosensory systems', 'https://nba.uth.tmc.edu/neuroscience/m/s2/chapter02.html'],
 motor: ['UTHealth · Motor cortex', 'https://nba.uth.tmc.edu/neuroscience/m/s3/chapter03.html'],
 folding: ['Tallinen et al. · On the growth and form of cortical convolutions', 'https://www.nature.com/articles/nphys3632'],
 split: ['de Haan et al. · Split-brain: what we know now', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7305066/'],
 model: ['Nilearn · FreeSurfer fsaverage surface data', 'https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_surf_fsaverage.html'],
 ventricles: ['NCBI Bookshelf · The ventricular system', 'https://www.ncbi.nlm.nih.gov/books/NBK532932/'],
 visioncortex: ['UTHealth · Visual cortical pathways', 'https://nba.uth.tmc.edu/neuroscience/m/s2/chapter15.html'],
 dopamine: ['Bhatia et al. · Dopamine receptor families', 'https://www.ncbi.nlm.nih.gov/books/NBK538242/'],
 glutamate: ['Purves et al. · Glutamate', 'https://www.ncbi.nlm.nih.gov/books/NBK10807/'],
 gaba: ['NCBI Bookshelf · GABA physiology', 'https://www.ncbi.nlm.nih.gov/books/NBK513311/'],
 glialresearch: ['Review · Astrocytes and microglia in development and homeostasis', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11102936/'],
 cortexanatomy: ['NCBI Bookshelf · The cerebral cortex', 'https://www.ncbi.nlm.nih.gov/books/NBK537247/'],
 amines: ['UTHealth · Biogenic amine neurotransmitters', 'https://nba.uth.tmc.edu/neuroscience/m/s1/chapter12.html'],
 acetylcholine: ['Purves et al. · Acetylcholine', 'https://www.ncbi.nlm.nih.gov/books/NBK11143/']
};

// Locations use FreeSurfer RAS millimetres. Deep structures are teaching approximations.
export const STRUCTURES = {
 cortex: {name:'Cerebral cortex',color:'#d6a48b',pos:[35,-10,45],where:'A thin, folded outer layer of the cerebral hemispheres.',does:'Transforms sensation, supports voluntary action, and participates in cognition.',care:'Even reading this sentence recruits several cortical systems.',deep:'Gray matter contains cell bodies, dendrites, synapses, glia, and axons. Under it, white matter contains many myelinated axons linking regions. Neither tissue works alone.',source:'basics'},
 left: {name:'Left hemisphere',color:'#c49d85',pos:[-35,-15,25],where:'The half on the person’s left. A front view reverses your screen’s left and right.',does:'Works with the right hemisphere; some functions are lateralized.',care:'Language is left-dominant in many people, but understanding and communicating draw on both sides.',deep:'Lateralization differs across functions and individuals. A hemisphere is not a personality type.',source:'laterality'},
 right: {name:'Right hemisphere',color:'#c49d85',pos:[35,-15,25],where:'The half on the person’s right, separated by the longitudinal fissure.',does:'Cooperates with the left; contributes strongly to some attention and spatial processes.',care:'Following a conversation also uses tone, context, and social cues.',deep:'Specialization and cooperation coexist. There is no evidence that people divide into global logical-left or creative-right brain types.',source:'laterality'},
 frontal: {name:'Frontal lobe',color:'#e9af87',pos:[36,37,25],where:'Behind your forehead, in front of the central sulcus.',does:'Supports action, planning, working memory, and aspects of executive control.',care:'Holding an idea in mind while resisting a distraction depends on interacting frontal and other systems.',deep:'Prefrontal regions interact with parietal, sensory, memory, and subcortical regions. Motor and premotor areas are also frontal. There is no single executive in charge.',source:'executive'},
 motor: {name:'Primary motor cortex',color:'#edba75',pos:[36,-12,52],where:'The precentral gyrus, just in front of the central sulcus.',does:'Helps generate descending signals for voluntary movement.',care:'Move your finger. Cortical signals join brainstem and spinal circuits to activate muscles.',deep:'Most corticospinal fibers cross in the lower medulla. Skilled movement also depends on premotor and supplementary motor areas, sensory feedback, basal ganglia, and cerebellum.',source:'motor'},
 parietal: {name:'Parietal lobe',color:'#b9c9ac',pos:[38,-49,48],where:'Behind the central sulcus, above the temporal lobe.',does:'Integrates touch, body position, spatial information, and attention.',care:'You can reach toward your phone without staring at your hand.',deep:'Its primary somatosensory cortex has an uneven body map: densely sensed parts have more representation. This homunculus is a functional map, not a tiny person inside the brain.',source:'somatic'},
 temporal: {name:'Temporal lobe',color:'#ce96a7',pos:[53,-20,-13],where:'At the sides, beneath the lateral sulcus.',does:'Supports hearing, recognition, language-related processing, and memory interactions.',care:'A familiar voice can become meaningful almost immediately.',deep:'Auditory cortex sits on the superior temporal plane. Ventral temporal regions contribute to object and face recognition. The hippocampus lies deeper in the medial temporal lobe.',source:'auditory'},
 occipital: {name:'Occipital lobe',color:'#8eb8cd',pos:[22,-91,12],where:'At the back of the cerebrum.',does:'Contains early visual cortical areas that interact with wider visual systems.',care:'What you see is an interpretation of light, shaped by context.',deep:'Retinal ganglion cells project through optic pathways to the lateral geniculate nucleus and other targets. LGN signals reach primary visual cortex. Feedback and parallel pathways matter too.',source:'visual'},
 thalamus: {name:'Thalamus',color:'#e8c174',pos:[13,-19,6],where:'Paired structures near the center, above the brainstem.',does:'Specialized nuclei participate in sensory processing, movement, attention, and cognition.',care:'What reaches awareness depends partly on how information is coordinated here.',deep:'The lateral geniculate nucleus participates in vision; the medial geniculate in hearing. Higher-order nuclei help coordinate cortical interactions. Olfaction does not require an initial thalamic relay to primary olfactory cortex.',source:'thalamus'},
 hypothalamus: {name:'Hypothalamus',color:'#df926b',pos:[0,-3,-12],where:'Below the thalamus, close to the third ventricle and pituitary.',does:'Coordinates internal regulation, including temperature, thirst, hunger, hormones, and rhythms.',care:'You do not need to consciously plan a thirst response.',deep:'Distinct hypothalamic nuclei integrate body signals and influence endocrine and autonomic systems. The suprachiasmatic nucleus helps synchronize daily timing with light information from the retina.',source:'hypothalamus'},
 hippocampus: {name:'Hippocampus',color:'#79cec0',pos:[27,-23,-16],where:'A curved structure deep in each medial temporal lobe.',does:'Helps form and retrieve episodic and relational memories.',care:'Remember your first day at school: a place, a person, a feeling.',deep:'Memory content involves distributed representations. Hippocampal interactions help bind elements of episodes. Consolidation changes these interactions over time; detailed episodic recollection may continue to involve the hippocampus.',source:'memory'},
 amygdala: {name:'Amygdala',color:'#dd8fa1',pos:[24,-4,-18],where:'In the anterior medial temporal lobe, ahead of the hippocampus.',does:'Participates in emotional learning and evaluating biologically relevant events.',care:'The same sound can mean danger, a celebration, or nothing—depending on learning and context.',deep:'The amygdala contains multiple nuclei and interacts with cortical, striatal, hypothalamic, and brainstem systems. It responds to rewarding as well as threatening information. It is not a fear button.',source:'amygdala'},
 basal: {name:'Basal ganglia',color:'#c8a8d5',pos:[24,2,5],where:'A set of deep nuclei, including the striatum and pallidum; related nuclei lie nearby and in the midbrain.',does:'Contributes to selecting actions, movement control, and learning.',care:'Typing a familiar word becomes more fluent with practice.',deep:'Cortex–basal ganglia–thalamus loops help shape behavior. Dopamine influences learning and movement in particular circuits. Skills also depend on cortex, cerebellum, sensory feedback, and practice.',source:'basal'},
 callosum: {name:'Corpus callosum',color:'#e9dcc0',pos:[0,-12,25],where:'An arch of white matter connecting the cerebral hemispheres.',does:'Carries signals between many regions of the two hemispheres.',care:'Your brain continually coordinates information across its two halves.',deep:'These are bundles of axons, not an empty bridge. Other interhemispheric pathways also exist; callosal surgery does not simply create two separate people.',source:'split'},
 ventricles: {name:'Ventricles',color:'#82b9d5',pos:[9,-16,18],where:'Connected fluid-filled spaces inside the brain.',does:'Contain cerebrospinal fluid, produced largely by the choroid plexus.',care:'Fluid helps support the brain and maintain its environment.',deep:'Lateral ventricles connect to the third ventricle, then the fourth through the cerebral aqueduct. CSF also circulates around the brain and spinal cord. The displayed fluid spaces are simplified.',source:'basics'},
 cerebellum: {name:'Cerebellum',color:'#d4ad79',pos:[25,-57,-37],where:'Behind the brainstem, below the occipital lobes.',does:'Supports timing, coordination, error-based learning, and functions beyond movement.',care:'Catching a ball means comparing what you predicted with what happened.',deep:'Cerebellar circuits contribute to motor and nonmotor functions. Counting studies estimate roughly 69 billion of the brain’s approximately 86 billion neurons are here, mostly tiny granule cells; estimates vary.',source:'cerebellum'},
 brainstem: {name:'Brainstem',color:'#c3b59b',pos:[0,-26,-36],where:'Between the deeper brain and spinal cord, in front of the cerebellum.',does:'Contains vital regulatory nuclei and major ascending and descending pathways.',care:'Breathing and wakefulness depend on distributed systems that include this region.',deep:'Its main divisions are the midbrain, pons, and medulla. These interact with forebrain and body systems. An evolutionary “reptilian brain” layered beneath newer brains is a misleading model.',source:'basics'},
 midbrain: {name:'Midbrain',color:'#dec6a5',pos:[0,-20,-15],where:'The upper brainstem, below the thalamus.',does:'Contributes to orienting, movement, and arousal.',care:'Turning toward an unexpected sight or sound recruits midbrain systems.',deep:'The superior and inferior colliculi participate in visual orienting and auditory processing. The substantia nigra contains dopamine-producing neurons important for movement-related circuits.',source:'parkinson'},
 pons: {name:'Pons',color:'#bcbba9',pos:[0,-25,-30],where:'Between midbrain and medulla, in front of the cerebellum.',does:'Participates in breathing, sleep, cranial nerve functions, and cerebellar communication.',care:'Coordination depends on signals passing through this region.',deep:'Pontine nuclei relay cortical information toward the cerebellum. Sleep and respiratory regulation involve networks spanning the pons, medulla, hypothalamus, and other regions.',source:'sleep'},
 medulla: {name:'Medulla',color:'#cba68b',pos:[0,-29,-47],where:'The lower brainstem, continuous with the spinal cord.',does:'Contains circuits involved in breathing and cardiovascular regulation.',care:'Your body keeps adjusting these functions while your attention is elsewhere.',deep:'The medulla also carries sensory and motor pathways. Many corticospinal axons cross here before descending in the spinal cord.',source:'motor'},
 spinal: {name:'Spinal cord',color:'#c6b99a',pos:[0,-28,-78],where:'Continues downward from the medulla, inside the vertebral column.',does:'Links brain and body and contains local sensory, motor, and reflex circuits.',care:'Muscles need spinal motor neurons to translate many brain commands into action.',deep:'A spinal reflex can begin before you consciously experience its trigger. The brain continually modulates spinal activity. Peripheral nerves extend from the central nervous system to the body.',source:'motor'}
};

const S=(title,hook,text,focus=[],view='brain',extra={})=>({title,hook,text,focus,view,duration:30,...extra});
export const CHAPTERS=[
 {name:'Meet your brain',title:'Meet your\nbrain.',subtitle:'The whole, before the parts.',scenes:[
 S('A world inside you.','Right now, this organ is making sense of these words.','Turn the brain. Notice the two hemispheres, the folded surface, and the smaller cerebellum tucked underneath. This surface comes from an MRI-derived research template.',[],'brain',{task:'Drag to rotate. Scroll or pinch to travel closer.',source:'model'}),
 S('Two sides. One conversation.','Your left is the brain’s left—not necessarily the left of your screen.','A deep fissure separates the cerebral hemispheres. They specialize in some tasks and continually cooperate.', ['left','right'],'hemispheres',{source:'laterality'}),
 S('Follow the shape.','The brain does not end at the cortex.','Below the cerebrum sits the cerebellum. In front of it, the brainstem connects downward to the spinal cord. Select a structure to keep its location in context.',['cerebellum','brainstem','spinal'],'brain',{task:'Select the cerebellum on the model.',challenge:'cerebellum',source:'basics'}),
 S('A map you can hold.','Make the surface transparent. The inside stays in place.','Rotate, zoom, pan, and separate the hemispheres. Anatomical colors are teaching aids; real tissue does not come color-coded.',['cortex'],'xray',{task:'Try X-ray, then select an inner structure.',source:'basics'})
 ]},
 {name:'The cortex',title:'A landscape\nof possibility.',subtitle:'Across the folded surface.',scenes:[
 S('Ridges and valleys.','The folds let a large cortical sheet fit into a compact volume.','A ridge is a gyrus; a groove is a sulcus. Differential tissue growth and physical constraints help shape these folds during development. More folds alone do not measure intelligence.',['cortex'],'cortex',{demo:'folds',source:'folding',deeper:'Folding reflects interactions among growth, tissue mechanics, and developmental patterning. The exact folding pattern varies across individuals; a research template is not every person’s brain.'}),
 S('Gray outside. White within.','A few millimeters can hold an extraordinary amount of circuitry.','Gray matter contains cell bodies, dendrites, synapses, glia, and axons. White matter contains many myelinated axons connecting regions. Both are living, complex tissue.',['cortex','callosum'],'section',{demo:'tissue',source:'basics'}),
 S('Before you act.','Imagine replying to a message—and choosing to wait.','Frontal systems help maintain goals, plan actions, and regulate responses. The primary motor cortex lies near the back of the frontal lobe. These systems work with many other regions.',['frontal','motor'],'brain',{demo:'inhibition',source:'executive',task:'When WAIT appears, hold back. When GO appears, tap.'}),
 S('Where is your hand?','Close your eyes for a moment. You still have a sense of your body.','Parietal systems combine touch, body position, vision, and attention. The sensory homunculus allocates more cortex to some body parts, such as the hands and lips.',['parietal'],'brain',{demo:'homunculus',source:'somatic',deeper:'The body map is approximate, overlapping, and adaptable. Size here represents cortical territory, not the body’s proportions or a literal little person.'}),
 S('A voice becomes meaning.','You recognize a friend without seeing their face.','Temporal systems analyze sound and interact with language and memory networks. Other temporal regions contribute to recognizing objects and faces. Language is more distributed than two named areas.',['temporal','hippocampus'],'brain',{demo:'hearing',source:'auditory'}),
 S('Seeing is constructing.','Your eyes receive light. Your brain constructs visual perception.','Visual systems extract and combine edges, orientation, color, motion, and form. Information flows through parallel pathways and feedback loops, influenced by context.',['occipital','temporal','parietal'],'vision',{demo:'illusion',source:'visual',task:'Compare the two center squares. Reveal their identical color.'})
 ]},
 {name:'Beneath the surface',title:'Beneath\nthe surface.',subtitle:'Deep structures. Constant conversations.',scenes:[
 S('The center is busy.','A great deal happens out of sight.','The cortex fades, but stays around the inner structures for orientation. The thalami, hippocampi, amygdalae, and basal ganglia use research meshes; selected connecting structures are simplified teaching models.',['thalamus','hippocampus','basal'],'xray',{task:'Rotate to see what lies beside, above, and behind each structure.',source:'model'}),
 S('More than a relay.','The thalamus helps coordinate what different systems exchange.','It contains specialized nuclei for sensory, motor, and cognitive interactions. Visual and auditory information use different thalamic pathways; smell is an exception to the usual initial sensory relay.',['thalamus','occipital','temporal'],'xray',{network:'sensory',source:'thalamus'}),
 S('Your first day.','Picture arriving at high school or college for the first time.','The hippocampus helps bind places, people, and events into an episode. The memory is not a little movie inside it: representations involve many cortical and subcortical regions.',['hippocampus','temporal','frontal'],'memory',{demo:'memory',source:'memory',deeper:'Systems consolidation changes hippocampal–cortical interactions over time. How the hippocampus supports remote, detailed episodic memories remains actively studied.'}),
 S('Meaning changes a response.','A sudden sound can be a threat—or the beginning of applause.','Amygdala circuits help learn and evaluate emotionally significant information. They interact with sensory systems, memories, body regulation, and context. Amygdala ≠ fear button.',['amygdala','hypothalamus','hippocampus','frontal'],'emotion',{demo:'context',source:'amygdala'}),
 S('Practice changes the next attempt.','Remember learning to type without watching your fingers.','Basal ganglia circuits contribute to action selection and learning. Repetition and feedback can make actions more fluent, alongside changes in cortical and cerebellar systems.',['basal','thalamus','motor'],'xray',{demo:'practice',network:'action',source:'basal'}),
 S('Keeping you in balance.','While you read, your brain is also taking care of your body.','Hypothalamic systems coordinate temperature, hunger, thirst, hormonal activity, circadian timing, and autonomic responses. Different circuits handle different aspects of internal regulation.',['hypothalamus','brainstem'],'body',{demo:'body',source:'hypothalamus'}),
 S('The small brain. The big surprise.','Most of your brain’s neurons are packed into the cerebellum.','One widely used estimate places about 69 of 86 billion neurons here—roughly four in five. Neuron count does not equal importance or a simple measure of intelligence.',['cerebellum'],'cerebellum',{demo:'neurons',source:'numbers'}),
 S('Catch. Compare. Adjust.','Catching a ball means predicting where it will be.','Cerebellar circuits help coordinate timing and correct errors as you move and learn. They also participate in cognitive and affective functions beyond movement.',['cerebellum','motor','parietal'],'brain',{demo:'catch',network:'action',source:'cerebellum'}),
 S('The essential connection.','Your next breath depends on networks you rarely notice.','Travel through midbrain, pons, and medulla. Brainstem circuits participate in breathing, cardiovascular regulation, arousal, and sleep, while major sensory and motor pathways pass through.',['midbrain','pons','medulla','spinal'],'stem',{source:'basics',deeper:'The brain did not evolve as three independent layers, with a reptilian core below emotion and reason. Evolution changed interconnected systems together.'}),
 S('The spaces within.','Not everything inside the brain is brain tissue.','The ventricles are connected spaces containing cerebrospinal fluid. Fluid circulates through them and around the brain and spinal cord, supporting and helping maintain the nervous system’s environment.',['ventricles'],'xray',{source:'basics'})
 ]},
 {name:'Crossing the brain',title:'Across\nthe divide.',subtitle:'Specialization without separation.',scenes:[
 S('A living bridge.','Many conversations cross from one hemisphere to the other.','The corpus callosum contains axons linking cortical regions. Separate the hemispheres to see its position, then watch representative signals cross in both directions.',['callosum','left','right'],'hemispheres',{network:'callosal',source:'split'}),
 S('You are not left-brained.','Logic and creativity do not live on opposite sides of your personality.','Some functions show hemispheric specialization. Most complex behaviors recruit distributed systems, often across both hemispheres. A popular personality division is not a scientific account of how your brain works.',['left','right','callosum'],'hemispheres',{network:'callosal',source:'laterality',task:'Reunite the hemispheres with Reset view.'})
 ]},
 {name:'Inside a neuron',title:'Meet\none neuron.',subtitle:'A different scale of life.',scenes:[
 S('Closer. Closer. A cell.','The cortex becomes a landscape of individual cells.','This is a schematic neuron. Dendrites receive many inputs; the cell body sustains the cell. The nucleus contains DNA. An axon carries signals toward its terminals.',[],'neuron',{demo:'neuron',source:'neurons',task:'Rotate the neuron. Select a part to discover its role.'}),
 S('A wave of change.','A signal is a changing electrical state—not a glowing object in a tube.','Ion channels change the voltage across the membrane. An action potential regenerates along the axon, usually beginning near the axon initial segment when sufficient inputs bring it to threshold.',[],'neuron',{demo:'potential',source:'neurons',task:'Trigger a signal. Slow it 1,000× to see the changing membrane state.',deeper:'In a typical neuron, voltage-gated sodium channels support rapid depolarization; sodium-channel inactivation and potassium currents help repolarize the membrane. Resting voltage and spike shape vary across cell types.'}),
 S('Insulate. Regenerate.','Myelin changes how efficiently a signal travels.','Myelin reduces current leakage and membrane capacitance. Action potentials regenerate at the gaps called nodes of Ranvier. Current spreads between them; the signal does not teleport.',[],'neuron',{demo:'myelin',source:'glia',task:'Switch myelin on and off. Compare illustrative conduction times.'})
 ]},
 {name:'Across a synapse',title:'Across\na tiny gap.',subtitle:'Electrical. Chemical. Electrical.',scenes:[
 S('The end is another beginning.','The axon terminal is close to the next cell—but usually does not touch it.','In this chemical synapse, an action potential opens voltage-gated calcium channels. Calcium entry triggers vesicles to fuse with the presynaptic membrane and release neurotransmitter.',[],'synapse',{demo:'synapse',source:'synapse',task:'Release a signal and follow it across the synaptic cleft.'}),
 S('A message needs a receiver.','The receptor helps determine what the message does.','Neurotransmitters bind receptors on the postsynaptic membrane. Some receptors directly control ion channels; others activate slower chemical signaling. A response may alter the chance or pattern of firing.',[],'synapse',{demo:'transmitters',source:'transmitters',deeper:'A typical chemical synaptic cleft spans tens of nanometers. Molecules diffuse and may bind, unbind, be taken up, or be broken down. The scene enlarges structures and slows time; molecular motion is illustrative.'}),
 S('Not a happiness chemical.','A molecule does not have a single psychological meaning.','Dopamine is involved in movement, motivation, and learning in different circuits. Serotonin has varied roles in regulation and behavior. Effects depend on receptor, location, state, and context.',[],'synapse',{demo:'transmitters',source:'transmitters',task:'Switch neurotransmitters, then compare the two dopamine receptor families.'})
 ]},
 {name:'The other cells',title:'Never\nalone.',subtitle:'The cells people forget.',scenes:[
 S('Astrocytes keep the neighborhood working.','A neuron depends on the environment around it.','Astrocytes help regulate extracellular ions, take up neurotransmitters, and support metabolism. Their endfeet interact with blood vessels; the blood–brain barrier relies chiefly on endothelial tight junctions.',[],'glia',{demo:'glia',glial:'astrocyte',source:'glia'}),
 S('One cell. Many stretches of myelin.','An oligodendrocyte can wrap segments of several axons.','In the central nervous system, oligodendrocytes form myelin and support axons. In peripheral nerves, Schwann cells perform the myelinating role.',[],'glia',{demo:'glia',glial:'oligodendrocyte',source:'glia'}),
 S('Watchful and responsive.','Microglia continually interact with the brain’s environment.','These resident immune cells survey tissue, respond to injury, and participate in removing debris and remodeling connections. The brain is a community of cell types, not neurons alone.',[],'glia',{demo:'glia',glial:'microglia',source:'glia'})
 ]},
 {name:'One to billions',title:'From cells\nto a mind.',subtitle:'The most important zoom out.',scenes:[
 S('No single neuron thinks.','A synapse belongs to a cell. A cell participates in circuits.','Many neurons receive thousands of synaptic contacts, though the number varies widely. Local circuits interact with broader networks. Behavior emerges through populations of cells working with the body and environment.',[],'circuit',{demo:'scale',source:'numbers',deeper:'A neuron can carry information relevant to a particular stimulus without containing the whole experience. A visualized network is a model of interactions, not a literal map of thought.'}),
 S('Different conversations. Shared participants.','Remembering, concentrating, and noticing involve changing patterns of cooperation.','Explore default mode, salience, control, and attention networks. Their names and boundaries summarize measured patterns; they are not isolated organs or glowing cables.',['frontal','parietal','temporal'],'network',{demo:'networks',network:'default',source:'networks'}),
 S('A map is not the mystery solved.','We can measure activity without fully explaining experience.','We know cells signal and networks interact. Network organization is a useful model. How these processes give rise to subjective experience remains an open scientific question.',[],'network',{demo:'evidence',network:'control',source:'networks',evidence:'We don’t yet know'})
 ]},
 {name:'A human experience',title:'Make\na moment.',subtitle:'Bring the systems together.',scenes:[
 S('See a familiar face.','Recognition begins long before you can name what you see.','Light reaches the retina. Retinal output travels through optic pathways, including the LGN, to visual cortex. Distributed visual systems interact with memory and knowledge as recognition unfolds.',['occipital','thalamus','temporal','hippocampus'],'vision',{demo:'experience',experience:'see',source:'visual'}),
 S('Hear your name.','A sound that matters can pull your attention toward it.','The cochlea converts vibrations into neural signals. Brainstem and midbrain pathways lead through auditory thalamus to auditory cortex. Attention and recognition involve wider systems.',['brainstem','thalamus','temporal','frontal'],'network',{demo:'experience',experience:'hear',source:'auditory'}),
 S('Move one finger.','An intention becomes an action through many stages.','Motor planning interacts with basal ganglia and cerebellar systems. Descending pathways reach spinal circuits; peripheral motor axons activate muscle at neuromuscular junctions. Sensory feedback helps guide the movement.',['frontal','motor','basal','cerebellum','spinal'],'body',{demo:'experience',experience:'move',source:'motor'}),
 S('Return to your childhood home.','Notice what arrives: a doorway, a room, a sound.','Retrieval involves hippocampal and cortical interactions, including imagery and knowledge. Memories are reconstructed; they are not perfect recordings waiting in a single storage location.',['hippocampus','temporal','frontal','occipital'],'memory',{demo:'experience',experience:'remember',source:'memory'}),
 S('Feel a moment change.','The same event can feel different in a different context.','Emotion involves interactions among brain, body, learning, and situation. Amygdala, insula, prefrontal, hypothalamic, and other systems contribute; no single region contains an entire emotion.',['amygdala','hypothalamus','frontal','hippocampus'],'emotion',{demo:'experience',experience:'feel',source:'amygdala'}),
 S('Think: 27 + 16.','Hold a number. Change it. Check the result.','Working memory, learned knowledge, attention, and control interact as you solve the problem. The parts matter. Their changing relationships explain much more than a single “thinking center.”',['frontal','parietal','thalamus'],'network',{demo:'experience',experience:'think',source:'executive',task:'Work it out, then reveal the answer and the systems involved.'})
 ]},
 {name:'Your brain never stops',title:'While\nyou sleep.',subtitle:'A different kind of activity.',scenes:[
 S('Day becomes night.','Falling asleep is a change in state, not a power switch.','Sleep and wakefulness are regulated by interacting brainstem, hypothalamic, and forebrain systems. Circadian timing and time spent awake both influence the tendency to sleep.',['hypothalamus','brainstem','thalamus'],'sleep',{demo:'sleep',sleep:'wake',source:'sleep'}),
 S('NREM. REM. Repeat.','The sleeping brain moves through changing patterns of activity.','Deeper NREM includes prominent slow waves; REM has relatively wake-like cortical activity, rapid eye movements, and reduced skeletal muscle tone. Dreaming can occur in both REM and NREM.',['thalamus','hippocampus','brainstem'],'sleep',{demo:'sleep',sleep:'nrem',source:'sleep'}),
 S('The work continues.','Sleep supports learning, regulation, and the body’s ongoing needs.','Memory-related activity changes during sleep, including coordinated hippocampal–cortical patterns. Researchers are still working out how different sleep processes contribute to memory and restoration.',['hippocampus','frontal','hypothalamus'],'sleep',{demo:'sleep',sleep:'rem',source:'sleep',evidence:'Our best model'}),
 S('And then, you wake.','Everything you saw… is happening inside you.','A synapse. A neuron. A circuit. A network. A brain. A person. And we have only begun to understand it.',[],'finale',{demo:'finale',source:'networks'})
 ]}
];

export const TRANSMITTERS=[
 {id:'glutamate',name:'Glutamate',color:'#e4ba73',receptor:'AMPA receptor',effect:'Usually excitatory at AMPA receptors: cation flow tends to depolarize the membrane.',detail:'A major excitatory transmitter in the brain. Receptor type matters: glutamate also acts at NMDA and metabotropic receptors.'},
 {id:'gaba',name:'GABA',color:'#91b9d8',receptor:'GABA-A receptor',effect:'Usually inhibitory in mature neurons: chloride conductance can oppose or shunt excitation.',detail:'The effect depends on ion gradients and membrane voltage. GABA-A is an ion channel; GABA-B uses a different signaling mechanism.'},
 {id:'dopamine',name:'Dopamine',color:'#d7a3c3',receptor:'D1-like / D2-like',effect:'Modulates cellular signaling; it is not a pleasure substance with one universal effect.',detail:'D1-like receptors typically increase cAMP signaling; D2-like receptors typically decrease it. Circuit effects are more complex than “on” and “off.”'},
 {id:'serotonin',name:'Serotonin',color:'#b4a7dc',receptor:'Multiple 5-HT receptor families',effect:'Can have different effects across receptors and circuits, including roles in sleep and behavioral regulation.',detail:'Most serotonin receptors act through G proteins; 5-HT3 is an ion channel. “Serotonin = happiness” misses this diversity.'},
 {id:'acetylcholine',name:'Acetylcholine',color:'#a4c9a4',receptor:'Nicotinic / muscarinic',effect:'Contributes to attention and state regulation in the brain; activates skeletal muscle at neuromuscular junctions.',detail:'Nicotinic receptors are ligand-gated ion channels. Muscarinic receptors use G-protein signaling; different subtypes produce different cellular effects.'},
 {id:'norepinephrine',name:'Norepinephrine',color:'#d99e80',receptor:'Alpha / beta adrenergic',effect:'Modulates arousal, attention, and responsiveness, depending on receptor and context.',detail:'The locus coeruleus supplies much of the brain’s norepinephrine. It does not act as a single “stress switch.”'}
];

export const NETWORKS={
 default:{name:'Default mode',hook:'When your mind turns inward.',text:'Often involved in autobiographical remembering, imagining, and aspects of social thought. It can cooperate with control networks during internally directed tasks.',nodes:['frontal','hippocampus','parietal'],points:[[0,52,-2],[0,-52,28],[-45,-65,30],[45,-65,30],[-27,-23,-16],[27,-23,-16]],color:'#9dc5bf'},
 salience:{name:'Salience',hook:'What deserves a change in attention?',text:'Anterior insular and dorsal anterior cingulate systems help detect relevant events and coordinate responses with other networks.',nodes:['frontal','amygdala','thalamus'],points:[[-32,20,0],[32,20,0],[0,20,35],[-13,-19,6],[13,-19,6]],color:'#e0a08f'},
 control:{name:'Frontoparietal control',hook:'Hold a goal. Adapt your next step.',text:'Frontal and parietal regions coordinate flexible, goal-directed behavior. “Control” describes an interacting network, not a tiny commander.',nodes:['frontal','parietal'],points:[[-40,35,30],[40,35,30],[-42,-50,45],[42,-50,45],[0,20,35]],color:'#c0b0db'},
 attention:{name:'Dorsal attention',hook:'Aim your attention at something.',text:'Frontal eye fields and intraparietal regions participate in selecting locations and features. Other attention systems help reorient you to unexpected events.',nodes:['frontal','parietal'],points:[[-25,0,50],[25,0,50],[-25,-55,55],[25,-55,55]],color:'#a9c9a1'}
};

export const EXPERIENCES={
 see:{name:'See',focus:['occipital','thalamus','temporal','hippocampus'],steps:['Light reaches retina','Optic pathways → LGN','Primary visual cortex','Visual association systems','Recognition + memory'],points:[[31,86,-10],[10,5,-12],[15,-26,3],[15,-92,5],[45,-50,-15],[27,-23,-16]],text:'Selected stages in a much richer, recurrent visual system. Some optic fibers cross at the chiasm; each hemisphere primarily processes the opposite visual field.'},
 hear:{name:'Hear',focus:['temporal','thalamus','brainstem','frontal'],steps:['Cochlea transduces sound','Auditory brainstem pathways','Inferior colliculus → MGN','Auditory cortex','Recognition + attention'],points:[[68,-5,-30],[10,-30,-35],[5,-30,-10],[15,-23,1],[48,-20,5],[36,35,30]],text:'Auditory pathways have extensive bilateral connections. This highlighted route is a selection, not a complete wiring diagram.'},
 move:{name:'Move',focus:['motor','basal','cerebellum','spinal'],steps:['Intention + motor planning','Motor circuits interact','Descending motor pathways','Spinal motor neurons','Peripheral nerve → muscle'],points:[[-36,25,40],[-24,2,5],[-36,-12,52],[0,-26,-36],[5,-28,-95],[110,-17,-190],[156,-15,-310],[160,0,-425]],text:'Many corticospinal fibers cross in the medulla. Basal ganglia and cerebellar loops interact with motor systems; they are not consecutive stations on one cable.'},
 remember:{name:'Remember',focus:['hippocampus','frontal','temporal','occipital'],steps:['A cue arrives','Hippocampal interactions','Distributed representations','Details reconstructed','A remembered experience'],points:[[36,35,30],[27,-23,-16],[53,-20,-13],[22,-91,12],[0,-52,28]],text:'A conceptual visualization of distributed retrieval. We cannot read the content of your own memory from this model.'},
 feel:{name:'Feel',focus:['amygdala','hypothalamus','hippocampus','frontal'],steps:['A meaningful event','Context + emotional learning','Body regulation','Body signals return','Experience unfolds'],points:[[53,-20,-13],[24,-4,-18],[0,-3,-12],[0,-26,-36],[32,20,0],[36,35,30]],text:'These interactions are recurrent, not a fixed recipe for an emotion. Individual experience depends on learning, body state, and context.'},
 think:{name:'Think',focus:['frontal','parietal','thalamus'],steps:['Hold 27 in mind','Add 10 → 37','Add 6 → 43','Check the result','43'],points:[[-40,35,30],[-42,-50,45],[42,-50,45],[40,35,30],[13,-19,6]],text:'Arithmetic draws on learned knowledge, working memory, attention, and control. The route is illustrative, not a scan of someone solving this sum.'}
};

export const WHATIFS=[
 {id:'split',title:'If the corpus callosum is severed',focus:['callosum','left','right'],text:'Some transfers of information between hemispheres become difficult. In classic controlled experiments, something presented briefly in the left visual field may be hard to name verbally when language is left-dominant, while the left hand may still identify it.',deeper:'Effects vary with the task, extent of surgery, other pathways, and adaptation. These operations have sometimes been used for severe epilepsy. They do not simply split a person into two personalities.',source:'split'},
 {id:'memory',title:'If both hippocampi are severely damaged',focus:['hippocampus','temporal','frontal'],text:'Forming new lasting episodic memories can become profoundly difficult. Some earlier memories, working memory, and skill learning may be relatively spared, depending on the damage.',deeper:'Different forms of memory depend on partly different systems. Outcomes vary with the cause and the extent of damage; this is not a prediction for an individual.',source:'memory'},
 {id:'dopamine',title:'If nigrostriatal dopamine neurons are lost',focus:['midbrain','basal','motor'],text:'Loss of dopamine-producing neurons in the substantia nigra disrupts movement-related basal ganglia circuits. In Parkinson’s disease, this contributes to slowness and stiffness; other motor and nonmotor features involve broader changes.',deeper:'Dopamine has multiple pathways and functions. Losing these cells does not mean losing all dopamine or all pleasure. This scene highlights an affected circuit, not the severity of someone’s symptoms.',source:'parkinson'},
 {id:'vision',title:'If part of primary visual cortex is damaged',focus:['occipital','thalamus'],text:'Damage can impair the corresponding region of the opposite visual field. The pattern depends on which visual cortical tissue is affected. Some people retain limited unconscious visual responses, called blindsight.',deeper:'Blindsight is variable and does not mean normal conscious vision. Other visual pathways and surviving tissue can contribute. This is a conceptual field map, not a simulation of anyone’s lived experience.',source:'visual'},
 {id:'coordination',title:'If cerebellar circuits are damaged',focus:['cerebellum','motor','parietal'],text:'The timing, precision, and coordination of movement can be disrupted. Someone may overshoot a target or have difficulty with balance. Effects depend on the affected circuits and may extend beyond movement.',deeper:'Ataxia describes impaired coordination, not necessarily weakness. The animation compares intended and variable trajectories to explain error correction, without representing any individual’s condition.',source:'cerebellum'}
];

export const SURPRISES=[
 {title:'Small volume. Enormous population.',text:'Roughly 80% of the neurons in one widely used whole-brain estimate are in the cerebellum. The glowing dots show a proportion—not individual neurons.',focus:['cerebellum'],demo:'neurons',view:'cerebellum',source:'numbers'},
 {title:'A demanding organ.',text:'The adult brain is about 2% of body mass but uses roughly 20% of resting energy. These are approximate averages, and age and physiological state matter.',focus:['cortex','cerebellum'],demo:'energy',view:'brain',source:'numbers'},
 {title:'The fastest route changes the membrane.',text:'Myelin allows current to spread farther and action potentials to regenerate at nodes. Toggle it to compare two illustrative conduction speeds.',focus:[],demo:'myelin',view:'neuron',source:'glia'},
 {title:'Same light. Different experience.',text:'The center squares have identical pixel values. Their surroundings change how you perceive them. Vision interprets relationships, not just isolated inputs.',focus:['occipital'],demo:'illusion',view:'vision',source:'visual'},
 {title:'Remembering is rebuilding.',text:'A cue can reactivate pieces of an episode across systems. The reconstruction can change with context and later information; remembering is not replaying a perfect recording.',focus:['hippocampus','temporal','frontal'],demo:'memory',view:'memory',source:'memory'}
];

export const SEARCH_SYSTEMS={
 memory:['hippocampus','temporal','frontal','amygdala'],vision:['occipital','thalamus','temporal','parietal'],language:['temporal','frontal','parietal','callosum'],movement:['motor','basal','cerebellum','brainstem','spinal'],attention:['frontal','parietal','thalamus'],emotion:['amygdala','hippocampus','hypothalamus','frontal'],sleep:['hypothalamus','brainstem','thalamus','cortex'],hearing:['temporal','thalamus','brainstem'],thinking:['frontal','parietal','thalamus'],body:['hypothalamus','brainstem','spinal']
};

// Scene-specific reading keeps general anatomy, mechanisms, and interpretations distinct.
STRUCTURES.cortex.source='cortexanatomy';
STRUCTURES.ventricles.source='ventricles';
CHAPTERS[1].scenes[1].source='cortexanatomy';
CHAPTERS[1].scenes[5].source='visioncortex';
CHAPTERS[2].scenes[9].source='ventricles';
CHAPTERS[5].scenes[2].source='amines';
CHAPTERS[6].scenes[0].source='glialresearch';
CHAPTERS[6].scenes[2].source='glialresearch';
CHAPTERS[8].scenes[3].source='plasticity';
SURPRISES[3].source='visioncortex';
SURPRISES[4].source='plasticity';
for(const nt of TRANSMITTERS) nt.source=({glutamate:'glutamate',gaba:'gaba',dopamine:'dopamine',serotonin:'amines',acetylcholine:'acetylcholine',norepinephrine:'amines'})[nt.id];

